services:
  xtts-finetune-webui:
    restart: unless-stopped
    # edit below to run on a container runtime other than nvidia-container-runtime.
    # not yet tested with rocm/AMD GPUs
    # Comment out the "deploy" section to run on CPU only
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility, compute]
              count: 1
    # Uncomment the image line to pull the image from the container registry.
    # Also, comment out the build section.
    #image: ghcr.io/matatonic/xtts-finetune-webui:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    init: true
    ports:
      - "5003:5003"
    volumes:
      - ./hf:/root/.cache/huggingface
      - ./output:/data/output
      - ./input:/data/input
